# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23dfd4f38b11208815bee8455c4705795bb6f55006584c1b528aa5889e74b0cd5eae9b79194e3947b3defcf023b4f0d3014c39628c66cba10f7f1d244786fe5d

test:
  secret_key_base: d4cd1c16e717796d74b05993006da915f796c1754d7bae3f8b508a0513bc06291759ea60574eca7dc08ec570b5854f27dbdd5da446ddf5829c43aba75d914898

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
